export const card_names = [
    'crab',
    'boat',
    'fish',
    'swimmer',
    'shark',
    'mermaid',
    'shell',
    'octopus',
    'penguin',
    'sailor',
    'lighthouse',
    'shoal of fish',
    'penguin colony',
    'captain'
] as const;

// TODO: game instructions use different naming than ColorADD site - pick a source of truth
export const colors = [
    'white',
    'black',
    'red',
    'light red',
    'dark red',
    'yellow',
    'light yellow',
    'dark yellow',
    'blue',
    'light blue',
    'dark blue',
    'orange',
    'light orange',
    'dark orange',
    'green',
    'light green',
    'dark green',
    'brown',
    'light brown',
    'dark brown',
    'violet',
    'light violet',
    'dark violet',
    'gray',
    'dark gray',
    'silver',
    'gold',
] as const;
